name: Docker Image CI/CD - Digital Twin

env:
  DOCKER_IMAGE: digital-twin
  DTM_CONTAINER: digital-twin-management
  FFT_DTM_CONTAINER: digital-twin-management-fft
  VERSION: 0.5.0-SNAPSHOT

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
         submodules: 'recursive'

    - name: Build
      run: |
          make build

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_ORG_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:${{ env.VERSION }} --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest

    - name: Push the Docker image
      run: |
          docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
          docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:      
      - name: SSH into VM and Deploy new Image with Docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username:  ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Fail script on first error
            set -e
            
            # Login to GitHub Container Registry
            echo "${{ secrets.CI_ORG_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Deploy new Image
            cd /root/modapto/system-deployment
            docker compose pull ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
            docker compose up -d --no-deps ${{ env.DTM_CONTAINER }}

            # Deploy new Image
            cd /root/modapto/fft-deployment
            docker compose up -d --no-deps ${{ env.FFT_DTM_CONTAINER }}

            # Restart DT Modules
            docker restart $(docker ps -q --filter "ancestor= ghcr.io/modapto/digital-twin " --filter "name=^modapto-module-")

            # Remove unused images
            docker image prune -f
            
            # Logout
            docker logout ghcr.io
